document.writeln("  <ul class=\"page-sidebar-menu\"> ");
document.writeln("   <li class=\"start active\"> <a href=\"main.html\"><span class=\"title\">管理主页</span> </a> </li> ");
document.writeln("   <li class=\"\"> <a href=\"javascript:;\"><span class=\"title\">系统设置</span></a> ");
document.writeln("    <ul class=\"sub-menu\"> ");
document.writeln("     <li> <a href=\"layout_horizontal_sidebar_menu.html\">系统参数设置</a> </li> ");
document.writeln("     <li> <a href=\"layout_horizontal_menu1.html\">赞助商设置</a> </li> ");
document.writeln("    </ul> </li> ");
document.writeln("   <li class=\"\"> <a href=\"javascript:;\"><span class=\"title\">驾校考场</span></a> ");
document.writeln("    <ul class=\"sub-menu\"> ");
document.writeln("     <li> <a href=\"../school/school_add_edit.html\">添加驾校</a> </li> ");
document.writeln("     <li> <a href=\"../school/school_school_list.html\">驾校列表</a> </li> ");
document.writeln("    </ul> </li> ");
document.writeln("   <li class=\"\"> <a href=\"javascript:;\"><span class=\"title\">教练管理</span></a> ");
document.writeln("    <ul class=\"sub-menu\"> ");
document.writeln("     <li> <a href=\"../techer/techer_add_edit.html\">添加教练</a> </li> ");
document.writeln("     <li> <a href=\"../techer/techer_view_list.html\">教练列表</a> </li> ");
document.writeln("    </ul> </li> ");
document.writeln("   <li class=\"\"> <a href=\"javascript:;\"><span class=\"title\">学员管理</span></a> ");
document.writeln("    <ul class=\"sub-menu\"> ");
document.writeln("     <li> <a href=\"../student/students_add.html\">添加学员</a> </li> ");
document.writeln("     <li> <a href=\"../../student/students_view_list.html\">学员列表</a> </li> ");
document.writeln("     <li> <a href=\"../student/students_view_list.html\">自由学员</a> </li> ");
document.writeln("     <li> <a href=\"../student/students_view_list.html\">包科二学员</a> </li> ");
document.writeln("     <li> <a href=\"../student/students_view_list.html\">包科三学员</a> </li> ");
document.writeln("     <li> <a href=\"../student/students_view_list.html\">尚未报名</a> </li> ");
document.writeln("     <li> <a href=\"../student/students_view_list.html\">拿证学员</a> </li> ");
document.writeln("    </ul> </li> ");
document.writeln("   <li> <a href=\"javascript:;\"><span class=\"title\">财务管理</span></a> ");
document.writeln("    <ul class=\"sub-menu\"> ");
document.writeln("     <li> <a href=\"../money/money.html\">财务汇总</a> </li> ");
document.writeln("     <li> <a href=\"../money/money_in_new.html\">费用充值</a> </li> ");
document.writeln("     <li> <a href=\"../money/money_checkout.html\">结算费用</a> </li> ");
document.writeln("     <li> <a href=\"../money/money_feed.html\">消费明细</a> </li> ");
document.writeln("    </ul> </li> ");
document.writeln("   <li> <a class=\"active\" href=\"javascript:;\"><span class=\"title\">评价管理</span></a> ");
document.writeln("    <ul class=\"sub-menu\"> ");
document.writeln("     <li> <a href=\"../comment/comment_view.html\">评价汇总</a> </li> ");
document.writeln("    </ul> </li> ");
document.writeln("   <li class=\"\"> <a href=\"javascript:;\"><span class=\"title\">订单管理</span></a> ");
document.writeln("    <ul class=\"sub-menu\"> ");
document.writeln("     <li> <a href=\"../order/order_list_yuyue.html\">查看订单</a> </li>; ");
document.writeln("    </ul> </li> ");
document.writeln("   <li class=\"\"> <a href=\"javascript:;\"><span class=\"title\">超管设置</span></a> ");
document.writeln("    <ul class=\"sub-menu\"> ");
document.writeln("     <li> <a href=\"login_soft.html\">网站超管</a> </li> ");
document.writeln("    </ul> </li> ");
document.writeln("  </ul>");
document.writeln("");